<?php

use App\Controllers\AdminCategoriesController;
use App\Controllers\AdminContactsController;
use App\Controllers\AdminOrdersController;
use App\Controllers\CartController;
use App\Controllers\HomeController;
use App\Controllers\AboutController;
use App\Controllers\ContactController;
use App\Controllers\ProductsController;
use App\Controllers\AuthController;
use App\Controllers\AdminController;
use App\Controllers\AdminProductController;
use App\Controllers\AdminUserController;
use App\Controllers\AdminSettingsController;
use Core\Router;

Router::get("/", HomeController::class, "index");
Router::get("/home", HomeController::class, "index");
Router::get("/about-us", AboutController::class, "index");
Router::get("/contact-us", ContactController::class, "index");
Router::post("/contact-us", ContactController::class, "store");
Router::get("/products", ProductsController::class, "index");
Router::get("/product", ProductsController::class, "show");
Router::post("/products/comment", ProductsController::class, "storeComment");
Router::get("/cart", CartController::class, "index");
Router::post("/cart/add", CartController::class, "add");
Router::post("/cart/increase", CartController::class, "increase");
Router::post("/cart/decrease", CartController::class, "decrease");
Router::post("/cart/remove", CartController::class, "remove");
Router::post("/cart/checkout", CartController::class, "checkout");
Router::get("/login", AuthController::class, "indexLogin");
Router::post("/login", AuthController::class, "login");
Router::get("/register", AuthController::class, "indexRegister");
Router::post("/register", AuthController::class, "Register");
Router::get("/admin", AuthController::class, "admin");
Router::post("/admin", AuthController::class, "adminLogin");
Router::get("/logout", AuthController::class, "logout" );
Router::get("/admin/dashboard", AdminController::class, "index");
Router::get("/admin/products", AdminProductController::class, "index");
Router::get("/admin/add-product", AdminProductController::class, "add");
Router::post("/admin/add-product", AdminProductController::class, "insert");
Router::get("/admin/edit-product", AdminProductController::class, "edit");
Router::post("/admin/update-product", AdminProductController::class, "update");
Router::post("/admin/delete-product", AdminProductController::class, "delete");
Router::get('/admin/users', AdminUserController::class, 'index');
Router::post('/admin/users/store', AdminUserController::class, 'store');
Router::post('/admin/users/update', AdminUserController::class, 'update');
Router::post('/admin/users/delete', AdminUserController::class, 'delete');
Router::get('/admin/users/get', AdminUserController::class, 'getUser');
Router::get("/admin/roles-permissions", AdminUserController::class, "roles");
Router::get("/admin/shop-settings", AdminSettingsController::class, "shopSettings");
Router::post("/admin/shop-settings", AdminSettingsController::class, "shopStore");
Router::get("/admin/public-settings", AdminSettingsController::class, "publicSettings");
Router::post("/admin/public-settings", AdminSettingsController::class, "publicStore");
Router::get("/admin/categories", AdminCategoriesController::class, "index");
Router::post("/admin/categories/store", AdminCategoriesController::class, "store");
Router::post("/admin/categories/update", AdminCategoriesController::class, "update");
Router::post("/admin/categories/delete", AdminCategoriesController::class, "delete");
Router::get("/admin/orders", AdminOrdersController::class, "index");
Router::get('/admin/orders/get', AdminOrdersController::class, "getOrder");
Router::get("/admin/orders/show", AdminOrdersController::class, "show");
Router::get("/admin/orders/edit", AdminOrdersController::class, "edit");
Router::post("/admin/orders/edit", AdminOrdersController::class, "updateStatus");
Router::get('/admin/contact-messages', AdminContactsController::class, "index");
Router::get('/admin/contact-messages/show', AdminContactsController::class, "show");
Router::post('/admin/contact-messages/delete', AdminContactsController::class, "delete");

Router::dispatch();